version: '3.4'

services:
  rabbit-mq:
    image: rabbitmq:3.8.14-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - sc-network

  zipkin-server:
    image: openzipkin/zipkin:2.23.2
    restart: always
    ports:
      - 9411:9411
    depends_on:
      - rabbit-mq
    environment:
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
    networks:
      - sc-network

  cambio-db:
    image: mysql:8.0.29
    command: mysqld --default_authentication_plugin=mysql_native_password
    restart: always
    ports:
      - 3308:3308
    expose:
      - 3308
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cambio_service
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    networks:
      - sc-network

  book-db:
    image: mysql:8.0.29
    command: mysqld --default_authentication_plugin=mysql_native_password
    restart: always
    ports:
      - 3310:3310
    expose:
      - 3310
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: book_service
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3310
    networks:
      - sc-network

  book-service:
    image: book-service
    restart: always
    build:
      context: .
      dockerfile: book-service/Dockerfile
    ports:
      - 8000:8000
    environment:
      SPRING.DATASOURCE.URL: jdbc:mysql://book-db:3310/book_service?useSSL=false&serverTimezone=UTC&enableTLSProtocols=TLSv1.2
      SPRING.DATASOURCE.USERNAME: "root"
      SPRING.DATASOURCE.PASSWORD: "root"
      SPRING.FLYWAY.URL: jdbc:mysql://book-db:3310/book_service?useSSL=false&serverTimezone=UTC&enableTLSProtocols=TLSv1.2
      SPRING.FLYWAY.USERNAME: "root"
      SPRING.FLYWAY.PASSWORD: "root"
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
    depends_on:
      - book-db
      - naming-server
      - rabbit-mq
    networks:
      - sc-network

  cambio-service:
    image: cambio-service
    restart: always
    build:
      context: .
      dockerfile: cambio-service/Dockerfile
    ports:
      - 8100:8100
    environment:
      SPRING.DATASOURCE.URL: jdbc:mysql://cambio-db:3308/cambio_service?useSSL=false&serverTimezone=UTC&enableTLSProtocols=TLSv1.2
      SPRING.DATASOURCE.USERNAME: "root"
      SPRING.DATASOURCE.PASSWORD: "root"
      SPRING.FLYWAY.URL: jdbc:mysql://cambio-db:3308/cambio_service?useSSL=false&serverTimezone=UTC&enableTLSProtocols=TLSv1.2
      SPRING.FLYWAY.USERNAME: "root"
      SPRING.FLYWAY.PASSWORD: "root"
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
    depends_on:
      - cambio-db
      - naming-server
      - rabbit-mq
    networks:
      - sc-network

  naming-server:
    image: naming-server
    restart: always
    build:
      context: .
      dockerfile: naming-server/Dockerfile
    ports:
      - 8761:8761
    networks:
      - sc-network

  api-gateway:
    image: api-gateway
    restart: always
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports:
      - 8765:8765
    depends_on:
      - naming-server
      - rabbit-mq
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
    networks:
      - sc-network

networks:
  sc-network:
    driver: bridge